// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orchestrator.Services;

#nullable disable

namespace Orchestrator.Migrations
{
    [DbContext(typeof(OrchDbContext))]
    [Migration("20250415091528_AddArtifacts")]
    partial class AddArtifacts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Orchestrator.DataModels.SavedInfo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(42)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSuccessAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SavedInfos");
                });

            modelBuilder.Entity("Orchestrator.DataModels.SavedInfo", b =>
                {
                    b.OwnsOne("Orchestrator.Utils.DbList<Orchestrator.DataModels.MirrorArtifact>", "Artifacts", b1 =>
                        {
                            b1.Property<string>("SavedInfoId")
                                .HasColumnType("TEXT");

                            b1.HasKey("SavedInfoId");

                            b1.ToTable("SavedInfos");

                            b1.ToJson("Artifacts");

                            b1.WithOwner()
                                .HasForeignKey("SavedInfoId");

                            b1.OwnsMany("Orchestrator.DataModels.MirrorArtifact", "Value", b2 =>
                                {
                                    b2.Property<string>("DbListSavedInfoId")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("__synthesizedOrdinal")
                                        .ValueGeneratedOnAddOrUpdate()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Description")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Priority")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("DbListSavedInfoId", "__synthesizedOrdinal");

                                    b2.ToTable("SavedInfos");

                                    b2.WithOwner()
                                        .HasForeignKey("DbListSavedInfoId");
                                });

                            b1.Navigation("Value");
                        });

                    b.Navigation("Artifacts")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
