variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  IMAGE_TAG_LATEST: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - deploy 

before_script:
  - docker info
  - docker login -u $CI_DEPLOY_USER -p $CI_DEPLOY_PASSWORD $CI_REGISTRY

build-manager:
  stage: build
  image: docker:26
  tags:
    - dind
  script:
    - docker pull $CI_REGISTRY/$IMAGE_TAG_LATEST || true
    - docker build --build-arg="APP_UID=$APP_UID" -t $IMAGE_TAG ./Orchestrator
    - docker tag $IMAGE_TAG $IMAGE_TAG_LATEST
    - docker push $IMAGE_TAG
    - docker push $IMAGE_TAG_LATEST

deploy:
  stage: deploy
  image: docker:26-cli
  tags:
    - dind
  only:
    - master
  script:
    - docker-compose up -d

