version: "3"

services:
  manager:
    image: git.zju.edu.cn:5050/zju-mirror/mirrorsdotnet
    restart: always
    ports:
      - 6000:80
    environment:
      - TZ=Aisa/Shanghai
    volumes:
      - /data/conf/mirrorsdotnet/config:/app/Configs
      - /data/storage:/app/Data
      - /data/conf/mirrorsdotnet/status:/app/Status
