version: "3"

services:
  manager:
    image: git.zju.edu.cn:5050/zju-mirror/orchestrator
    container_name: orch
    restart: always
    ports:
      - 127.0.0.1:6003:8080
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /srv/orchestrator/appsettings.json:/app/appsettings.json:ro
      - /srv/mono-conf/orch/Configs/:/app/Configs:ro
      - /srv/orchestrator/data:/app/Data
