# Basic Info
Name:
  en: Debian
  zh: Debian 发行版
Description:
  en: Debian Packages
  zh: Debian 发行版包
Url: /debian
Location: /data/root/debian
HelpUrl: /help/debian
Type: Normal

# Sync Config
ProviderImage: xxx/xxxx
Upstream: 'https://mirrors.bfsu.edu.cn/debian'
ExtraArgs: -6
Cron: '*/1 * * * *'
