# Basic Info
Name:
  en: Debian
  zh: Debian 发行版
Description:
  en: Debian Packages
  zh: Debian 发行版包
Url: /debian
Location: /Data/debian
HelpUrl: /help/debian
Type: Normal

# Sync Config
Upstream: 'https://mirrors.bfsu.edu.cn/debian'
Cron: '*/1 * * * *'
Timeout: '5h'
Container:
  Image: 'workload:b'
  Pull: 'never'
  Volumes:
    - Source: '/tmp/workertest'
      Target: '/workdir'
    - Source: '/tmp/workertest/ro'
      Target: '/workdir'
      ReadOnly: true
  Command: 
    - '/app/workload'
    - '--some-cli-flag'
  Environments:
    - 'WORKLOAD_CNT=100'
  Name: 'job-debian-sync'
