# Basic Info
Name:
  en: Debian
  zh: Debian
Description:
  en: Debian Packages
  zh: Debian Packages
Url: /debian
HelpUrl: /help/debian
Type: Normal

# Sync Config
ProviderImage: xxx/xxxx
Upstream: 'https://mirrors.bfsu.edu.cn/debian'
ExtraArgs: -6
Cron: 0 0/1 * * * ?
