# Basic Info
Name:
  en: Debian CD
  zh: Debian 安装映像
Description:
  en: Debian Images
  zh: Debian 安装映像
Url: /debian-cd
Location: /data/root/debian-cd
Type: ProxyCache

# Index Job
TrigIndex: debian-iso  # will trig index job after sync success
