DisplayName: Debian
Description: Debian Packages
Url: /debian
HelpUrl: /help/debian
Type: ProxyCache

ProviderImage: xxx/xxxx
Upstream: https://mirrors.bfsu.edu.cn/debian
# ExtraArgs:
Cron: 0 * * * * *

DisplayIndex: debian-iso
